# Generated by Django 4.2.2 on 2023-09-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartquizzz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartQuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('languages', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('starttime', models.PositiveIntegerField()),
                ('runtime', models.PositiveIntegerField()),
                ('branch', models.CharField(max_length=255)),
                ('extrainfo', models.TextField()),
                ('maxQuestion', models.PositiveIntegerField()),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('hint', models.TextField()),
                ('option1', models.TextField()),
                ('option2', models.TextField()),
                ('option3', models.TextField()),
                ('option4', models.TextField()),
                ('severity', models.CharField(max_length=255)),
                ('avgTimeToAnswer', models.PositiveIntegerField()),
                ('marks', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='question',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='user',
        ),
        migrations.DeleteModel(
            name='QuizHistory',
        ),
        migrations.DeleteModel(
            name='QuizQuestion',
        ),
        migrations.DeleteModel(
            name='QuizResult',
        ),
        migrations.DeleteModel(
            name='UserResponse',
        ),
    ]
